daysUntilStale: 30
daysUntilClose: 30
markComment: >
  This PR has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs.
only: pulls
closeComment: >
  This PR was closed due to inactivity.
