name: BC Check
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  bc_check:
    name: Backwards Compatibility Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check for BC breaks
        uses: docker://nyholm/roave-bc-check-ga
