name: Code Coverage
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  coverage:
    name: Report Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: composer install
      - name: Generate Coverage
        run: composer phpunit -- --coverage-clover ./build/logs/clover.xml
      - name: Publish Coverage
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ./build/logs/clover.xml
